name: future_soket
description: wrapper for Socket, has methodh await read(count_byte).
version: 1.0.1
repository: https://github.com/AndreiLosev/future_soket

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
